# Red Wine Quality Analysis using Numpy Part-I

# 225229150-BALAMURUGAN P

# import modules for numpy

In [19]:
import numpy as np

In [20]:
wines=np.genfromtxt("winequality-red.csv",delimiter=';',skip_header=1)
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [21]:
wines.shape

(1599, 12)

In [22]:
wines.shape[0]

1599

In [23]:
wines.shape[1]

12

In [24]:
wines.ndim

2

In [25]:
type(wines)

numpy.ndarray

In [26]:
wines.dtype

dtype('float64')

In [27]:
wines[:5]

array([[7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00, 5.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00, 5.000e+00],
       [1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02, 1.700e+01,
        6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00, 6.000e+00],
       [7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00]])

In [28]:
wines[2][3]

2.3

In [29]:
wines[:3,3]

array([1.9, 2.6, 2.3])

In [30]:
wines[::,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [31]:
wines[1,::]

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

In [32]:
wines[1:4,4]

array([0.098, 0.092, 0.075])

In [33]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [34]:
#updated
wines[0,0]=100
wines[0,0]

100.0

In [35]:
wines[0,0]=7.4

In [48]:
x=wines[3,:]
x

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [49]:
x[1]

0.28

In [50]:
wines.astype(int)

array([[ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       ...,
       [ 6,  0,  0, ...,  0, 11,  6],
       [ 5,  0,  0, ...,  0, 10,  5],
       [ 6,  0,  0, ...,  0, 11,  6]])

# Vectorization Operations

In [51]:
wines[::,11]

array([5., 5., 5., ..., 6., 5., 6.])

In [52]:
a=wines[::,11]+10
a

array([15., 15., 15., ..., 16., 15., 16.])

In [53]:
wines[::,10]

array([ 9.4,  9.8,  9.8, ..., 11. , 10.2, 11. ])

In [54]:
b=wines[::,10]*3
b

array([28.2, 29.4, 29.4, ..., 33. , 30.6, 33. ])

In [55]:
c=a+a
c

array([30., 30., 30., ..., 32., 30., 32.])

In [44]:
d=a*b
d

array([423., 441., 441., ..., 528., 459., 528.])

# Broadcasting

In [45]:
rand_array=np.random.random((12))

In [46]:
rand_array

array([0.32587576, 0.18164413, 0.60165082, 0.12777308, 0.27185085,
       0.55259742, 0.78490148, 0.14264881, 0.18432243, 0.10539707,
       0.15712316, 0.04869062])

In [47]:
wines+rand_array

array([[ 7.72587576,  0.88164413,  0.60165082, ...,  0.66539707,
         9.55712316,  5.04869062],
       [ 8.12587576,  1.06164413,  0.60165082, ...,  0.78539707,
         9.95712316,  5.04869062],
       [ 8.12587576,  0.94164413,  0.64165082, ...,  0.75539707,
         9.95712316,  5.04869062],
       ...,
       [ 6.62587576,  0.69164413,  0.73165082, ...,  0.85539707,
        11.15712316,  6.04869062],
       [ 6.22587576,  0.82664413,  0.72165082, ...,  0.81539707,
        10.35712316,  5.04869062],
       [ 6.32587576,  0.49164413,  1.07165082, ...,  0.76539707,
        11.15712316,  6.04869062]])